# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitdir < Formula
  desc "Download specific directories from GitHub repositories at lightning speed."
  homepage "https://github.com/Ameen-Sha-Cheerangan/GitDir"
  version "1.0.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Ameen-Sha-Cheerangan/GitDir/releases/download/v1.0.4/gitdir_Darwin_x86_64.tar.gz"
      sha256 "1dd97e58e47104ab4a758826ff569331469a2f7d2df070c82d44f9c35d3c78e5"

      def install
        bin.install "gitdir"
      end
    end
    on_arm do
      url "https://github.com/Ameen-Sha-Cheerangan/GitDir/releases/download/v1.0.4/gitdir_Darwin_arm64.tar.gz"
      sha256 "53bb30c81cf7a0c1e3169cea2251c1449f02aa951f3e791303b5e631c4dbb260"

      def install
        bin.install "gitdir"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ameen-Sha-Cheerangan/GitDir/releases/download/v1.0.4/gitdir_Linux_x86_64.tar.gz"
        sha256 "742c174682fe6ad36cbbc8a8976777ac26ec7e8f1a1c14a2f4d0b61bfb0a7203"

        def install
          bin.install "gitdir"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ameen-Sha-Cheerangan/GitDir/releases/download/v1.0.4/gitdir_Linux_arm64.tar.gz"
        sha256 "8063d9a6d29a84f8375af6e8b2172c9c16f107316b22c25ee8d44f1006d7b147"

        def install
          bin.install "gitdir"
        end
      end
    end
  end
end
