# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitdir < Formula
  desc "Download specific directories from GitHub repositories at lightning speed."
  homepage "https://github.com/Ameen-Sha-Cheerangan/GitDir"
  version "1.1.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Ameen-Sha-Cheerangan/GitDir/releases/download/v1.1.5/gitdir_Darwin_x86_64.tar.gz"
      sha256 "c885459b5fd57286616f81339589a9ad96b15a67423a10e73209fad05f6a9760"

      def install
        bin.install "gitdir"
      end
    end
    on_arm do
      url "https://github.com/Ameen-Sha-Cheerangan/GitDir/releases/download/v1.1.5/gitdir_Darwin_arm64.tar.gz"
      sha256 "6a023e6e766452dad20fea63b2f4e7d6342792de8f721f7262e5a5bd8fc7a7d8"

      def install
        bin.install "gitdir"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ameen-Sha-Cheerangan/GitDir/releases/download/v1.1.5/gitdir_Linux_x86_64.tar.gz"
        sha256 "fdccb5fb38cdb452fe278ddb6244f9884a515bb8a46fa68515fcc09175a2c3b2"

        def install
          bin.install "gitdir"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ameen-Sha-Cheerangan/GitDir/releases/download/v1.1.5/gitdir_Linux_arm64.tar.gz"
        sha256 "91211a76378f4cd6a298a7769b323508db41325a0c5f06473059a1e85158eabe"

        def install
          bin.install "gitdir"
        end
      end
    end
  end
end
