# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitdir < Formula
  desc "Download specific directories from GitHub repositories at lightning speed."
  homepage "https://github.com/Ameen-Sha-Cheerangan/GitDir"
  version "1.1.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Ameen-Sha-Cheerangan/GitDir/releases/download/v1.1.6/gitdir_Darwin_x86_64.tar.gz"
      sha256 "58b9416cb868af1919a1ccec268979cc8b5ef584d49b1d5506437af1c457ba3d"

      def install
        bin.install "gitdir"
      end
    end
    on_arm do
      url "https://github.com/Ameen-Sha-Cheerangan/GitDir/releases/download/v1.1.6/gitdir_Darwin_arm64.tar.gz"
      sha256 "c854448cdf7d7c42bd1e59af9f88436c729719ca9cc621a996c1e35fb54e2d52"

      def install
        bin.install "gitdir"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ameen-Sha-Cheerangan/GitDir/releases/download/v1.1.6/gitdir_Linux_x86_64.tar.gz"
        sha256 "42a411f9b93a42b49e397cb317f831c1280e0341c3bcc007f28c3fe996b2c20f"

        def install
          bin.install "gitdir"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Ameen-Sha-Cheerangan/GitDir/releases/download/v1.1.6/gitdir_Linux_arm64.tar.gz"
        sha256 "2fb5d507f810eff38da09598e7ab4f6aefdaac908655bb1330bba5f9f0f174dd"

        def install
          bin.install "gitdir"
        end
      end
    end
  end
end
